name: Publish Release

on:
  workflow_dispatch:
  push:
    branches:
      - release

jobs:
  test:
    name: Test
    permissions:
      contents: read
    uses: ./.github/workflows/func-test.yml
  build-jar:
    name: Build Jar
    needs: test
    permissions:
      contents: read
    uses: ./.github/workflows/func-build-jar.yml
  publish-release:
    name: Publish Production Release
    needs: build-jar
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v8
        with:
          name: ${{ needs.build-jar.outputs.ARTIFACT_ID }}
          path: build/libs
      - name: Calculate Date Version
        id: date
        run: echo "VERSION=$(date +'%Y.%m.%d').${{ github.run_number }}" >> $GITHUB_ENV
      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ env.VERSION }}
          tag_name: v${{ env.VERSION }}
          generate_release_notes: true
          make_latest: true
          files: build/libs/jdbcli.jar

